
"""
Inker Robotics Pvt Ltd 
Developed on Feb 2021
Hardware Designed and Developed by:Er.Anu Antony
Software and Logic Designed and Developed by:Er.Akhil P Jacob

"""

from PyQt5 import QtCore, QtGui, QtWidgets
from Robot_Guidance_System import PhysicalParamTester
from FireBase import fireRTDB_update
from MAPPER import MAPPING
import time
import csv

X1=0
X2=0
X3=0
XF=0
Y1=0
Y2=0
Y3=0
YF=0

class TCSL(object):
    def tcsil(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(594, 534)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GraphiX/index.jfif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 571, 401))
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 127);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(40, 20, 16, 17))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 50, 16, 17))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(40, 80, 16, 17))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(40, 110, 16, 17))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setGeometry(QtCore.QRect(40, 140, 16, 17))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_6.setGeometry(QtCore.QRect(40, 170, 16, 17))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_7.setGeometry(QtCore.QRect(40, 350, 16, 17))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_8.setGeometry(QtCore.QRect(40, 200, 16, 17))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_9.setGeometry(QtCore.QRect(40, 230, 16, 17))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_10.setGeometry(QtCore.QRect(40, 320, 16, 17))
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_11.setGeometry(QtCore.QRect(40, 260, 16, 17))
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_12.setGeometry(QtCore.QRect(40, 290, 16, 17))
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_13.setGeometry(QtCore.QRect(70, 170, 16, 17))
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_14.setGeometry(QtCore.QRect(70, 320, 16, 17))
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_15.setGeometry(QtCore.QRect(70, 230, 16, 17))
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_16.setGeometry(QtCore.QRect(70, 200, 16, 17))
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_17.setGeometry(QtCore.QRect(70, 260, 16, 17))
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_18.setGeometry(QtCore.QRect(70, 290, 16, 17))
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_19.setGeometry(QtCore.QRect(70, 20, 16, 17))
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_20.setGeometry(QtCore.QRect(70, 50, 16, 17))
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_21.setGeometry(QtCore.QRect(70, 140, 16, 17))
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_22.setGeometry(QtCore.QRect(70, 80, 16, 17))
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_23.setGeometry(QtCore.QRect(70, 350, 16, 17))
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_24.setGeometry(QtCore.QRect(70, 110, 16, 17))
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_25.setGeometry(QtCore.QRect(100, 170, 16, 17))
        self.checkBox_25.setText("")
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_26.setGeometry(QtCore.QRect(100, 320, 16, 17))
        self.checkBox_26.setText("")
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_27.setGeometry(QtCore.QRect(100, 230, 16, 17))
        self.checkBox_27.setText("")
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_28.setGeometry(QtCore.QRect(100, 200, 16, 17))
        self.checkBox_28.setText("")
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_29.setGeometry(QtCore.QRect(100, 260, 16, 17))
        self.checkBox_29.setText("")
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_30.setGeometry(QtCore.QRect(100, 290, 16, 17))
        self.checkBox_30.setText("")
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_31 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_31.setGeometry(QtCore.QRect(100, 20, 16, 17))
        self.checkBox_31.setText("")
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_32.setGeometry(QtCore.QRect(100, 50, 16, 17))
        self.checkBox_32.setText("")
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_33 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_33.setGeometry(QtCore.QRect(100, 140, 16, 17))
        self.checkBox_33.setText("")
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_34.setGeometry(QtCore.QRect(100, 80, 16, 17))
        self.checkBox_34.setText("")
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_35 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_35.setGeometry(QtCore.QRect(100, 350, 16, 17))
        self.checkBox_35.setText("")
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_36.setGeometry(QtCore.QRect(100, 110, 16, 17))
        self.checkBox_36.setText("")
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_37.setGeometry(QtCore.QRect(130, 170, 16, 17))
        self.checkBox_37.setText("")
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_38.setGeometry(QtCore.QRect(130, 320, 16, 17))
        self.checkBox_38.setText("")
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_39.setGeometry(QtCore.QRect(130, 230, 16, 17))
        self.checkBox_39.setText("")
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_40.setGeometry(QtCore.QRect(130, 200, 16, 17))
        self.checkBox_40.setText("")
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_41.setGeometry(QtCore.QRect(130, 260, 16, 17))
        self.checkBox_41.setText("")
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_42.setGeometry(QtCore.QRect(130, 290, 16, 17))
        self.checkBox_42.setText("")
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_43.setGeometry(QtCore.QRect(130, 20, 16, 17))
        self.checkBox_43.setText("")
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_44.setGeometry(QtCore.QRect(130, 50, 16, 17))
        self.checkBox_44.setText("")
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_45 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_45.setGeometry(QtCore.QRect(130, 140, 16, 17))
        self.checkBox_45.setText("")
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkBox_46 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_46.setGeometry(QtCore.QRect(130, 80, 16, 17))
        self.checkBox_46.setText("")
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkBox_47 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_47.setGeometry(QtCore.QRect(130, 350, 16, 17))
        self.checkBox_47.setText("")
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_48 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_48.setGeometry(QtCore.QRect(130, 110, 16, 17))
        self.checkBox_48.setText("")
        self.checkBox_48.setObjectName("checkBox_48")
        self.checkBox_49 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_49.setGeometry(QtCore.QRect(160, 170, 16, 17))
        self.checkBox_49.setText("")
        self.checkBox_49.setObjectName("checkBox_49")
        self.checkBox_50 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_50.setGeometry(QtCore.QRect(160, 320, 16, 17))
        self.checkBox_50.setText("")
        self.checkBox_50.setObjectName("checkBox_50")
        self.checkBox_51 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_51.setGeometry(QtCore.QRect(160, 230, 16, 17))
        self.checkBox_51.setText("")
        self.checkBox_51.setObjectName("checkBox_51")
        self.checkBox_52 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_52.setGeometry(QtCore.QRect(160, 200, 16, 17))
        self.checkBox_52.setText("")
        self.checkBox_52.setObjectName("checkBox_52")
        self.checkBox_53 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_53.setGeometry(QtCore.QRect(160, 260, 16, 17))
        self.checkBox_53.setText("")
        self.checkBox_53.setObjectName("checkBox_53")
        self.checkBox_54 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_54.setGeometry(QtCore.QRect(160, 290, 16, 17))
        self.checkBox_54.setText("")
        self.checkBox_54.setObjectName("checkBox_54")
        self.checkBox_55 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_55.setGeometry(QtCore.QRect(160, 20, 16, 17))
        self.checkBox_55.setText("")
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_56 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_56.setGeometry(QtCore.QRect(160, 50, 16, 17))
        self.checkBox_56.setText("")
        self.checkBox_56.setObjectName("checkBox_56")
        self.checkBox_57 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_57.setGeometry(QtCore.QRect(160, 140, 16, 17))
        self.checkBox_57.setText("")
        self.checkBox_57.setObjectName("checkBox_57")
        self.checkBox_58 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_58.setGeometry(QtCore.QRect(160, 80, 16, 17))
        self.checkBox_58.setText("")
        self.checkBox_58.setObjectName("checkBox_58")
        self.checkBox_59 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_59.setGeometry(QtCore.QRect(160, 350, 16, 17))
        self.checkBox_59.setText("")
        self.checkBox_59.setObjectName("checkBox_59")
        self.checkBox_60 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_60.setGeometry(QtCore.QRect(160, 110, 16, 17))
        self.checkBox_60.setText("")
        self.checkBox_60.setObjectName("checkBox_60")
        self.checkBox_61 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_61.setGeometry(QtCore.QRect(190, 170, 16, 17))
        self.checkBox_61.setText("")
        self.checkBox_61.setObjectName("checkBox_61")
        self.checkBox_62 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_62.setGeometry(QtCore.QRect(190, 320, 16, 17))
        self.checkBox_62.setText("")
        self.checkBox_62.setObjectName("checkBox_62")
        self.checkBox_63 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_63.setGeometry(QtCore.QRect(190, 230, 16, 17))
        self.checkBox_63.setText("")
        self.checkBox_63.setObjectName("checkBox_63")
        self.checkBox_64 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_64.setGeometry(QtCore.QRect(190, 200, 16, 17))
        self.checkBox_64.setText("")
        self.checkBox_64.setObjectName("checkBox_64")
        self.checkBox_65 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_65.setGeometry(QtCore.QRect(190, 260, 16, 17))
        self.checkBox_65.setText("")
        self.checkBox_65.setObjectName("checkBox_65")
        self.checkBox_66 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_66.setGeometry(QtCore.QRect(190, 290, 16, 17))
        self.checkBox_66.setText("")
        self.checkBox_66.setObjectName("checkBox_66")
        self.checkBox_67 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_67.setGeometry(QtCore.QRect(190, 20, 16, 17))
        self.checkBox_67.setText("")
        self.checkBox_67.setObjectName("checkBox_67")
        self.checkBox_68 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_68.setGeometry(QtCore.QRect(190, 50, 16, 17))
        self.checkBox_68.setText("")
        self.checkBox_68.setObjectName("checkBox_68")
        self.checkBox_69 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_69.setGeometry(QtCore.QRect(190, 140, 16, 17))
        self.checkBox_69.setText("")
        self.checkBox_69.setObjectName("checkBox_69")
        self.checkBox_70 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_70.setGeometry(QtCore.QRect(190, 80, 16, 17))
        self.checkBox_70.setText("")
        self.checkBox_70.setObjectName("checkBox_70")
        self.checkBox_71 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_71.setGeometry(QtCore.QRect(190, 350, 16, 17))
        self.checkBox_71.setText("")
        self.checkBox_71.setObjectName("checkBox_71")
        self.checkBox_72 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_72.setGeometry(QtCore.QRect(190, 110, 16, 17))
        self.checkBox_72.setText("")
        self.checkBox_72.setObjectName("checkBox_72")
        self.checkBox_73 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_73.setGeometry(QtCore.QRect(220, 170, 16, 17))
        self.checkBox_73.setText("")
        self.checkBox_73.setObjectName("checkBox_73")
        self.checkBox_74 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_74.setGeometry(QtCore.QRect(220, 320, 16, 17))
        self.checkBox_74.setText("")
        self.checkBox_74.setObjectName("checkBox_74")
        self.checkBox_75 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_75.setGeometry(QtCore.QRect(220, 230, 16, 17))
        self.checkBox_75.setText("")
        self.checkBox_75.setObjectName("checkBox_75")
        self.checkBox_76 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_76.setGeometry(QtCore.QRect(220, 200, 16, 17))
        self.checkBox_76.setText("")
        self.checkBox_76.setObjectName("checkBox_76")
        self.checkBox_77 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_77.setGeometry(QtCore.QRect(220, 260, 16, 17))
        self.checkBox_77.setText("")
        self.checkBox_77.setObjectName("checkBox_77")
        self.checkBox_78 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_78.setGeometry(QtCore.QRect(220, 290, 16, 17))
        self.checkBox_78.setText("")
        self.checkBox_78.setObjectName("checkBox_78")
        self.checkBox_79 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_79.setGeometry(QtCore.QRect(220, 20, 16, 17))
        self.checkBox_79.setText("")
        self.checkBox_79.setObjectName("checkBox_79")
        self.checkBox_80 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_80.setGeometry(QtCore.QRect(220, 50, 16, 17))
        self.checkBox_80.setText("")
        self.checkBox_80.setObjectName("checkBox_80")
        self.checkBox_81 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_81.setGeometry(QtCore.QRect(220, 140, 16, 17))
        self.checkBox_81.setText("")
        self.checkBox_81.setObjectName("checkBox_81")
        self.checkBox_82 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_82.setGeometry(QtCore.QRect(220, 80, 16, 17))
        self.checkBox_82.setText("")
        self.checkBox_82.setObjectName("checkBox_82")
        self.checkBox_83 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_83.setGeometry(QtCore.QRect(220, 350, 16, 17))
        self.checkBox_83.setText("")
        self.checkBox_83.setObjectName("checkBox_83")
        self.checkBox_84 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_84.setGeometry(QtCore.QRect(220, 110, 16, 17))
        self.checkBox_84.setText("")
        self.checkBox_84.setObjectName("checkBox_84")
        self.checkBox_85 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_85.setGeometry(QtCore.QRect(250, 170, 16, 17))
        self.checkBox_85.setText("")
        self.checkBox_85.setObjectName("checkBox_85")
        self.checkBox_86 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_86.setGeometry(QtCore.QRect(250, 320, 16, 17))
        self.checkBox_86.setText("")
        self.checkBox_86.setObjectName("checkBox_86")
        self.checkBox_87 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_87.setGeometry(QtCore.QRect(250, 230, 16, 17))
        self.checkBox_87.setText("")
        self.checkBox_87.setObjectName("checkBox_87")
        self.checkBox_88 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_88.setGeometry(QtCore.QRect(250, 200, 16, 17))
        self.checkBox_88.setText("")
        self.checkBox_88.setObjectName("checkBox_88")
        self.checkBox_89 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_89.setGeometry(QtCore.QRect(250, 260, 16, 17))
        self.checkBox_89.setText("")
        self.checkBox_89.setObjectName("checkBox_89")
        self.checkBox_90 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_90.setGeometry(QtCore.QRect(250, 290, 16, 17))
        self.checkBox_90.setText("")
        self.checkBox_90.setObjectName("checkBox_90")
        self.checkBox_91 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_91.setGeometry(QtCore.QRect(250, 20, 16, 17))
        self.checkBox_91.setText("")
        self.checkBox_91.setObjectName("checkBox_91")
        self.checkBox_92 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_92.setGeometry(QtCore.QRect(250, 50, 16, 17))
        self.checkBox_92.setText("")
        self.checkBox_92.setObjectName("checkBox_92")
        self.checkBox_93 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_93.setGeometry(QtCore.QRect(250, 140, 16, 17))
        self.checkBox_93.setText("")
        self.checkBox_93.setObjectName("checkBox_93")
        self.checkBox_94 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_94.setGeometry(QtCore.QRect(250, 80, 16, 17))
        self.checkBox_94.setText("")
        self.checkBox_94.setObjectName("checkBox_94")
        self.checkBox_95 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_95.setGeometry(QtCore.QRect(250, 350, 16, 17))
        self.checkBox_95.setText("")
        self.checkBox_95.setObjectName("checkBox_95")
        self.checkBox_96 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_96.setGeometry(QtCore.QRect(250, 110, 16, 17))
        self.checkBox_96.setText("")
        self.checkBox_96.setObjectName("checkBox_96")
        self.checkBox_97 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_97.setGeometry(QtCore.QRect(280, 170, 16, 17))
        self.checkBox_97.setText("")
        self.checkBox_97.setObjectName("checkBox_97")
        self.checkBox_98 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_98.setGeometry(QtCore.QRect(280, 320, 16, 17))
        self.checkBox_98.setText("")
        self.checkBox_98.setObjectName("checkBox_98")
        self.checkBox_99 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_99.setGeometry(QtCore.QRect(280, 230, 16, 17))
        self.checkBox_99.setText("")
        self.checkBox_99.setObjectName("checkBox_99")
        self.checkBox_100 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_100.setGeometry(QtCore.QRect(280, 200, 16, 17))
        self.checkBox_100.setText("")
        self.checkBox_100.setObjectName("checkBox_100")
        self.checkBox_101 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_101.setGeometry(QtCore.QRect(280, 260, 16, 17))
        self.checkBox_101.setText("")
        self.checkBox_101.setObjectName("checkBox_101")
        self.checkBox_102 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_102.setGeometry(QtCore.QRect(280, 290, 16, 17))
        self.checkBox_102.setText("")
        self.checkBox_102.setObjectName("checkBox_102")
        self.checkBox_103 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_103.setGeometry(QtCore.QRect(280, 20, 16, 17))
        self.checkBox_103.setText("")
        self.checkBox_103.setObjectName("checkBox_103")
        self.checkBox_104 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_104.setGeometry(QtCore.QRect(280, 50, 16, 17))
        self.checkBox_104.setText("")
        self.checkBox_104.setObjectName("checkBox_104")
        self.checkBox_105 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_105.setGeometry(QtCore.QRect(280, 140, 16, 17))
        self.checkBox_105.setText("")
        self.checkBox_105.setObjectName("checkBox_105")
        self.checkBox_106 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_106.setGeometry(QtCore.QRect(280, 80, 16, 17))
        self.checkBox_106.setText("")
        self.checkBox_106.setObjectName("checkBox_106")
        self.checkBox_107 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_107.setGeometry(QtCore.QRect(280, 350, 16, 17))
        self.checkBox_107.setText("")
        self.checkBox_107.setObjectName("checkBox_107")
        self.checkBox_108 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_108.setGeometry(QtCore.QRect(280, 110, 16, 17))
        self.checkBox_108.setText("")
        self.checkBox_108.setObjectName("checkBox_108")
        self.checkBox_109 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_109.setGeometry(QtCore.QRect(310, 170, 16, 17))
        self.checkBox_109.setText("")
        self.checkBox_109.setObjectName("checkBox_109")
        self.checkBox_110 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_110.setGeometry(QtCore.QRect(310, 320, 16, 17))
        self.checkBox_110.setText("")
        self.checkBox_110.setObjectName("checkBox_110")
        self.checkBox_111 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_111.setGeometry(QtCore.QRect(310, 230, 16, 17))
        self.checkBox_111.setText("")
        self.checkBox_111.setObjectName("checkBox_111")
        self.checkBox_112 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_112.setGeometry(QtCore.QRect(310, 200, 16, 17))
        self.checkBox_112.setText("")
        self.checkBox_112.setObjectName("checkBox_112")
        self.checkBox_113 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_113.setGeometry(QtCore.QRect(310, 260, 16, 17))
        self.checkBox_113.setText("")
        self.checkBox_113.setObjectName("checkBox_113")
        self.checkBox_114 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_114.setGeometry(QtCore.QRect(310, 290, 16, 17))
        self.checkBox_114.setText("")
        self.checkBox_114.setObjectName("checkBox_114")
        self.checkBox_115 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_115.setGeometry(QtCore.QRect(310, 20, 16, 17))
        self.checkBox_115.setText("")
        self.checkBox_115.setObjectName("checkBox_115")
        self.checkBox_116 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_116.setGeometry(QtCore.QRect(310, 50, 16, 17))
        self.checkBox_116.setText("")
        self.checkBox_116.setObjectName("checkBox_116")
        self.checkBox_117 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_117.setGeometry(QtCore.QRect(310, 140, 16, 17))
        self.checkBox_117.setText("")
        self.checkBox_117.setObjectName("checkBox_117")
        self.checkBox_118 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_118.setGeometry(QtCore.QRect(310, 80, 16, 17))
        self.checkBox_118.setText("")
        self.checkBox_118.setObjectName("checkBox_118")
        self.checkBox_119 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_119.setGeometry(QtCore.QRect(310, 350, 16, 17))
        self.checkBox_119.setText("")
        self.checkBox_119.setObjectName("checkBox_119")
        self.checkBox_120 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_120.setGeometry(QtCore.QRect(310, 110, 16, 17))
        self.checkBox_120.setText("")
        self.checkBox_120.setObjectName("checkBox_120")
        self.checkBox_121 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_121.setGeometry(QtCore.QRect(340, 170, 16, 17))
        self.checkBox_121.setText("")
        self.checkBox_121.setObjectName("checkBox_121")
        self.checkBox_122 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_122.setGeometry(QtCore.QRect(340, 320, 16, 17))
        self.checkBox_122.setText("")
        self.checkBox_122.setObjectName("checkBox_122")
        self.checkBox_123 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_123.setGeometry(QtCore.QRect(340, 230, 16, 17))
        self.checkBox_123.setText("")
        self.checkBox_123.setObjectName("checkBox_123")
        self.checkBox_124 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_124.setGeometry(QtCore.QRect(340, 200, 16, 17))
        self.checkBox_124.setText("")
        self.checkBox_124.setObjectName("checkBox_124")
        self.checkBox_125 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_125.setGeometry(QtCore.QRect(340, 260, 16, 17))
        self.checkBox_125.setText("")
        self.checkBox_125.setObjectName("checkBox_125")
        self.checkBox_126 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_126.setGeometry(QtCore.QRect(340, 290, 16, 17))
        self.checkBox_126.setText("")
        self.checkBox_126.setObjectName("checkBox_126")
        self.checkBox_127 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_127.setGeometry(QtCore.QRect(340, 20, 16, 17))
        self.checkBox_127.setText("")
        self.checkBox_127.setObjectName("checkBox_127")
        self.checkBox_128 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_128.setGeometry(QtCore.QRect(340, 50, 16, 17))
        self.checkBox_128.setText("")
        self.checkBox_128.setObjectName("checkBox_128")
        self.checkBox_129 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_129.setGeometry(QtCore.QRect(340, 140, 16, 17))
        self.checkBox_129.setText("")
        self.checkBox_129.setObjectName("checkBox_129")
        self.checkBox_130 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_130.setGeometry(QtCore.QRect(340, 80, 16, 17))
        self.checkBox_130.setText("")
        self.checkBox_130.setObjectName("checkBox_130")
        self.checkBox_131 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_131.setGeometry(QtCore.QRect(340, 350, 16, 17))
        self.checkBox_131.setText("")
        self.checkBox_131.setObjectName("checkBox_131")
        self.checkBox_132 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_132.setGeometry(QtCore.QRect(340, 110, 16, 17))
        self.checkBox_132.setText("")
        self.checkBox_132.setObjectName("checkBox_132")
        self.checkBox_133 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_133.setGeometry(QtCore.QRect(370, 170, 16, 17))
        self.checkBox_133.setText("")
        self.checkBox_133.setObjectName("checkBox_133")
        self.checkBox_134 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_134.setGeometry(QtCore.QRect(370, 320, 16, 17))
        self.checkBox_134.setText("")
        self.checkBox_134.setObjectName("checkBox_134")
        self.checkBox_135 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_135.setGeometry(QtCore.QRect(370, 230, 16, 17))
        self.checkBox_135.setText("")
        self.checkBox_135.setObjectName("checkBox_135")
        self.checkBox_136 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_136.setGeometry(QtCore.QRect(370, 200, 16, 17))
        self.checkBox_136.setText("")
        self.checkBox_136.setObjectName("checkBox_136")
        self.checkBox_137 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_137.setGeometry(QtCore.QRect(370, 260, 16, 17))
        self.checkBox_137.setText("")
        self.checkBox_137.setObjectName("checkBox_137")
        self.checkBox_138 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_138.setGeometry(QtCore.QRect(370, 290, 16, 17))
        self.checkBox_138.setText("")
        self.checkBox_138.setObjectName("checkBox_138")
        self.checkBox_139 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_139.setGeometry(QtCore.QRect(370, 20, 16, 17))
        self.checkBox_139.setText("")
        self.checkBox_139.setObjectName("checkBox_139")
        self.checkBox_140 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_140.setGeometry(QtCore.QRect(370, 50, 16, 17))
        self.checkBox_140.setText("")
        self.checkBox_140.setObjectName("checkBox_140")
        self.checkBox_141 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_141.setGeometry(QtCore.QRect(370, 140, 16, 17))
        self.checkBox_141.setText("")
        self.checkBox_141.setObjectName("checkBox_141")
        self.checkBox_142 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_142.setGeometry(QtCore.QRect(370, 80, 16, 17))
        self.checkBox_142.setText("")
        self.checkBox_142.setObjectName("checkBox_142")
        self.checkBox_143 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_143.setGeometry(QtCore.QRect(370, 350, 16, 17))
        self.checkBox_143.setText("")
        self.checkBox_143.setObjectName("checkBox_143")
        self.checkBox_144 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_144.setGeometry(QtCore.QRect(370, 110, 16, 17))
        self.checkBox_144.setText("")
        self.checkBox_144.setObjectName("checkBox_144")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(410, 60, 151, 31))
        self.pushButton.setStyleSheet("color: rgb(0, 0, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 140, 151, 31))
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(410, 20, 151, 31))
        self.lineEdit.setStyleSheet("font: 5pt \"MS Shell Dlg 2\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(410, 100, 151, 31))
        self.lineEdit_2.setStyleSheet("font: 5pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 220, 151, 31))
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(410, 180, 151, 31))
        self.lineEdit_6.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 290, 151, 31))
        self.pushButton_6.setStyleSheet("color: rgb(204, 0, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 330, 151, 31))
        self.pushButton_7.setStyleSheet("color: rgb(92, 53, 102);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(470, 260, 31, 21))
        self.pushButton_9.setStyleSheet("background-color: rgb(115, 210, 22);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(520, 260, 31, 21))
        self.pushButton_10.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(420, 260, 31, 21))
        self.pushButton_8.setStyleSheet("background-color: rgb(204, 0, 0);")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 30, 41, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 77, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 70, 41, 20))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(30, 70, 77, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(370, 30, 41, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(370, 70, 41, 20))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(280, 70, 75, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(280, 30, 75, 17))
        self.label_10.setObjectName("label_10")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 280, 521, 31))
        self.pushButton_5.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setGeometry(QtCore.QRect(20, 320, 521, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(280, 170, 75, 17))
        self.label_11.setObjectName("label_11")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 130, 41, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(370, 170, 41, 20))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(30, 170, 77, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(280, 130, 75, 17))
        self.label_13.setObjectName("label_13")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 170, 41, 20))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(370, 130, 41, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 130, 77, 17))
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 420, 121, 111))
        self.label_4.setStyleSheet("border-image: url(GraphiX/aavdm6ll9u4rejqcjjij.ico);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 420, 131, 111))
        self.label.setStyleSheet("border-image: url(GraphiX/firebase.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(280, 420, 111, 111))
        self.label_5.setStyleSheet("border-image: url(GraphiX/Debian-Logo-.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(400, 420, 181, 91))
        self.label_6.setStyleSheet("border-image: url(GraphiX/logo.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")


        self.pushButton.clicked.connect(self.GET_INITIALPOSITIONS)
        self.pushButton_2.clicked.connect(self.GET_FINALPOSITION)
        self.pushButton_3.clicked.connect(self.GET_PHYSICS)
        self.pushButton_6.clicked.connect(self.PUSH_TO_CLOUD)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Task Coordination Intelligence for Single location"))
        self.pushButton.setText(_translate("Dialog", "Initial Robot Position"))
        self.pushButton_2.setText(_translate("Dialog", "Final End Point"))
        self.pushButton_3.setText(_translate("Dialog", "Do Physics"))
        self.pushButton_6.setText(_translate("Dialog", "UPLOAD"))
        self.pushButton_7.setText(_translate("Dialog", "EMPTY"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "TCISL"))
        self.label_7.setText(_translate("Dialog", "X1 Position"))
        self.label_8.setText(_translate("Dialog", "X2 Position"))
        self.label_9.setText(_translate("Dialog", "y2 Position"))
        self.label_10.setText(_translate("Dialog", "y1 Position"))
        self.pushButton_5.setText(_translate("Dialog", "SAVE"))
        self.label_11.setText(_translate("Dialog", "y4 Position"))
        self.label_12.setText(_translate("Dialog", "X4 Position"))
        self.label_13.setText(_translate("Dialog", "y3 Position"))
        self.label_14.setText(_translate("Dialog", "X3 Position"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "INITIAL ROBOT POSITIONS"))

    def GET_INITIALPOSITIONS(self):
        global X1,X2,X3,XF,Y1,Y2,Y3,YF
        print('[analyzing INIT POINTS]')
        LIST_CHKBXK=[]
        # LIST_CHKBXK.append("checkBox")
        # print(self.tab.findChildQtWidgets.QCheckBox, "checkBoxEnabled"))
        for i in self.tab.findChildren(QtWidgets.QCheckBox):
                LIST_CHKBXK.append(i)
        LIST_STATUS=[]
        CHOSEN_LOCATION=[]
        for i in LIST_CHKBXK:
                chk=i
                LIST_STATUS=chk.isChecked()
                if LIST_STATUS:
                        print(chk.objectName())
                        
                        positions=MAPPING.mapper(str(chk.objectName()))                        
                        CHOSEN_LOCATION.append(positions)
                        
        print(CHOSEN_LOCATION)
        Tom=CHOSEN_LOCATION[0]
        Popoye=CHOSEN_LOCATION[1]
        Denver=CHOSEN_LOCATION[2]    

        X1=Tom[0]
        Y1=Tom[1]
        X2=Popoye[0]
        Y2=Popoye[1]
        X3=Denver[0]
        Y3=Denver[1]

        print(X1,Y1,X2,Y2,X3,Y3)
        self.lineEdit.setText(str(CHOSEN_LOCATION))

    def GET_FINALPOSITION(self):
        global X1,X2,X3,XF,Y1,Y2,Y3,YF
        print('[analyzing FINAL POINTS]')
        LIST_CHKBXK=[]
        # LIST_CHKBXK.append("checkBox")
        # print(self.tab.findChildQtWidgets.QCheckBox, "checkBoxEnabled"))
        for i in self.tab.findChildren(QtWidgets.QCheckBox):
                LIST_CHKBXK.append(i)
        LIST_STATUS=[]        
        for i in LIST_CHKBXK:
                chk=i
                LIST_STATUS=chk.isChecked()
                if LIST_STATUS:
                        print(chk.objectName())
                        
                        positions=MAPPING.mapper(str(chk.objectName()))                        
                        XF=positions[0]
                        YF=positions[1]
                        self.lineEdit_2.setText(str(XF)+" "+str(YF))

    def GET_PHYSICS(self):
       
        Direction=PhysicalParamTester.Physics2(XF,YF,X1,X2,X3,Y1,Y2,Y3,300,300)
        self.lineEdit_6.setText(str(Direction))
        print(Direction)


    def PUSH_TO_CLOUD(self):
        data=str(self.lineEdit_6.text())    
        fireRTDB_update.fireRTDB_push(data)   
        print('[UPLOADED to CLOUD]')         

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = TCSL()
    ui.tcsil(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
